version: "3"

services:
  backend:
    build: ./backend
    command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../archivos:/backend/backend/media/uploads/:rw
    ports:
      - "8000:8000"
    networks:
      - opticanostra-network
    depends_on: 
      - postgres_app
    env_file:
      - ./backend/backend/backend/.env
    

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - opticanostra-network
    depends_on: 
      - postgres_app

  postgres_app:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    networks:
      - opticanostra-network
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    volumes:
      - snellendb:/var/lib/postgresql/data:rw
      
volumes:
  snellendb:

networks:
  opticanostra-network:
    external: true