version: "3"

services:
  backend:
    build: ./backend
    command: sh -c "python3 manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ../archivos:/backend/backend/media/uploads/:rw
    ports:
      - "8000:8000"
    networks:
      - opticanostra-network
    restart: always
    depends_on: 
      - mysql
    env_file:
      - ./backend/backend/backend/.env
    

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - opticanostra-network
    depends_on: 
      - mysql
    env_file:
      - ./frontend/frontend/.env

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    networks:
      - opticanostra-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: opticanostra
    volumes:
      - opticanostra-db:/var/lib/mysql:rw

volumes:
  opticanostra-db:

networks:
  opticanostra-network:
    external: true
