version: "3"

services:
  backend:
    build: ./backend
    command: sh -c "cd backend && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/backend/backend/.env

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  postgres_app:
    image: postgres:15.3-alpine3.18
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test
    volumes:
      - snellendb:/var/lib/postgresql/data:rw
      
volumes:
  snellendb: