# Generated by Django 4.1.7 on 2023-03-18 14:43

from django.db import migrations, models
import shortuuid.django_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', db_index=True, editable=False, length=10, max_length=10, prefix='', primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], max_length=9, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254, null=True)),
                ('telefono_movil', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono Móvil')),
                ('telefono_fijo', models.CharField(blank=True, max_length=12, null=True, verbose_name='Teléfono Fijo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
