# Generated by Django 4.1.7 on 2023-03-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0003_alter_receta_od_add_alter_receta_od_axis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='od_horizontal_direction',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='od_vertical_direction',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='oi_horizontal_direction',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='oi_vertical_direction',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
