# Generated by Django 4.1.7 on 2023-03-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0004_alter_receta_od_horizontal_direction_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receta',
            old_name='paciente_uuid',
            new_name='paciente',
        ),
        migrations.AlterField(
            model_name='receta',
            name='od_axis',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
