# Generated by Django 4.1.7 on 2023-07-16 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0007_armazon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armazon',
            name='uuid',
            field=models.PositiveBigIntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
