# Generated by Django 4.1.7 on 2023-07-17 00:19

from django.db import migrations, models
import optica.models


class Migration(migrations.Migration):

    dependencies = [
        ('optica', '0008_alter_armazon_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='armazon',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to=optica.models.armazon_foto_name),
        ),
    ]
